# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '_guncelleme.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Guncelleme(object):
    def setupUi(self, Guncelleme):
        Guncelleme.setObjectName("Guncelleme")
        Guncelleme.resize(605, 437)

        Guncelleme.setFixedSize(605, 437)

        self.lblTakip = QtWidgets.QLabel(Guncelleme)
        self.lblTakip.setGeometry(QtCore.QRect(120, 20, 361, 41))
        self.lblTakip.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTakip.setObjectName("lblTakip")
        self.lblTalimat = QtWidgets.QLabel(Guncelleme)
        self.lblTalimat.setGeometry(QtCore.QRect(50, 350, 501, 41))
        self.lblTalimat.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTalimat.setObjectName("lblTalimat")
        self.btnKaydet = QtWidgets.QPushButton(Guncelleme)
        self.btnKaydet.setGeometry(QtCore.QRect(250, 300, 111, 31))
        self.btnKaydet.setObjectName("btnKaydet")
        self.lnVeriGiris = QtWidgets.QLineEdit(Guncelleme)
        self.lnVeriGiris.setGeometry(QtCore.QRect(340, 240, 211, 31))
        self.lnVeriGiris.setObjectName("lnVeriGiris")
        self.cmbxVeriler = QtWidgets.QComboBox(Guncelleme)
        self.cmbxVeriler.setGeometry(QtCore.QRect(50, 240, 221, 31))
        self.cmbxVeriler.setObjectName("cmbxVeriler")
        self.cmbxListe = QtWidgets.QComboBox(Guncelleme)
        self.cmbxListe.setGeometry(QtCore.QRect(170, 80, 261, 31))
        self.cmbxListe.setObjectName("cmbxListe")
        self.btnSecim = QtWidgets.QPushButton(Guncelleme)
        self.btnSecim.setGeometry(QtCore.QRect(450, 80, 101, 31))
        self.btnSecim.setObjectName("btnSecim")
        self.lblIstenen = QtWidgets.QLabel(Guncelleme)
        self.lblIstenen.setGeometry(QtCore.QRect(40, 80, 101, 31))
        self.lblIstenen.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblIstenen.setObjectName("lblIstenen")
        self.cmbxListe_2 = QtWidgets.QComboBox(Guncelleme)
        self.cmbxListe_2.setGeometry(QtCore.QRect(170, 140, 261, 31))
        self.cmbxListe_2.setObjectName("cmbxListe_2")
        self.btnSecim_2 = QtWidgets.QPushButton(Guncelleme)
        self.btnSecim_2.setGeometry(QtCore.QRect(450, 140, 101, 31))
        self.btnSecim_2.setObjectName("btnSecim_2")
        self.lblIstenen_2 = QtWidgets.QLabel(Guncelleme)
        self.lblIstenen_2.setGeometry(QtCore.QRect(40, 140, 101, 31))
        self.lblIstenen_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblIstenen_2.setObjectName("lblIstenen_2")

        self.retranslateUi(Guncelleme)
        QtCore.QMetaObject.connectSlotsByName(Guncelleme)

    def retranslateUi(self, Guncelleme):
        _translate = QtCore.QCoreApplication.translate
        Guncelleme.setWindowTitle(_translate("Guncelleme", "Form"))
        self.lblTakip.setText(_translate("Guncelleme", "<html><head/><body><p><span style=\" font-size:11pt;\">Takip</span></p></body></html>"))
        self.lblTalimat.setText(_translate("Guncelleme", "<html><head/><body><p><span style=\" font-size:11pt;\">Talimatlar</span></p></body></html>"))
        self.btnKaydet.setText(_translate("Guncelleme", "Veriyi Güncelle"))
        self.btnSecim.setText(_translate("Guncelleme", "Seçim"))
        self.lblIstenen.setText(_translate("Guncelleme", "<html><head/><body><p><span style=\" font-size:9pt;\">Müşteri</span></p></body></html>"))
        self.btnSecim_2.setText(_translate("Guncelleme", "Seçim"))
        self.lblIstenen_2.setText(_translate("Guncelleme", "<html><head/><body><p><span style=\" font-size:10pt;\">Makina</span></p></body></html>"))
