# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '_musteriEkleme.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widget_musteriEkle(object):
    def setupUi(self, widget_musteriEkle):
        widget_musteriEkle.setObjectName("widget_musteriEkle")
        widget_musteriEkle.resize(521, 317)

        widget_musteriEkle.setFixedSize(521, 317)

        self.ln_musteriAd = QtWidgets.QLineEdit(widget_musteriEkle)
        self.ln_musteriAd.setGeometry(QtCore.QRect(220, 60, 131, 31))
        self.ln_musteriAd.setObjectName("ln_musteriAd")
        self.ln_musteriBolge = QtWidgets.QLineEdit(widget_musteriEkle)
        self.ln_musteriBolge.setGeometry(QtCore.QRect(220, 120, 131, 31))
        self.ln_musteriBolge.setObjectName("ln_musteriBolge")
        self.lbl_musteriAd = QtWidgets.QLabel(widget_musteriEkle)
        self.lbl_musteriAd.setGeometry(QtCore.QRect(130, 60, 71, 31))
        self.lbl_musteriAd.setObjectName("lbl_musteriAd")
        self.lbl_musteriBolge = QtWidgets.QLabel(widget_musteriEkle)
        self.lbl_musteriBolge.setGeometry(QtCore.QRect(130, 120, 71, 31))
        self.lbl_musteriBolge.setObjectName("lbl_musteriBolge")
        self.pushButton = QtWidgets.QPushButton(widget_musteriEkle)
        self.pushButton.setGeometry(QtCore.QRect(220, 170, 131, 31))
        self.pushButton.setObjectName("pushButton")
        self.lbl = QtWidgets.QLabel(widget_musteriEkle)
        self.lbl.setGeometry(QtCore.QRect(220, 220, 211, 41))
        self.lbl.setText("")
        self.lbl.setObjectName("lbl")

        self.retranslateUi(widget_musteriEkle)
        QtCore.QMetaObject.connectSlotsByName(widget_musteriEkle)

    def retranslateUi(self, widget_musteriEkle):
        _translate = QtCore.QCoreApplication.translate
        widget_musteriEkle.setWindowTitle(_translate("widget_musteriEkle", "Form"))
        self.lbl_musteriAd.setText(_translate("widget_musteriEkle", "Müşteri Adı:"))
        self.lbl_musteriBolge.setText(_translate("widget_musteriEkle", "Müşteri Bölge:"))
        self.pushButton.setText(_translate("widget_musteriEkle", "Kaydet"))
